-- AlterTable
ALTER TABLE "users" ADD COLUMN     "lastQueryDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "plan" TEXT NOT NULL DEFAULT 'FREE',
ADD COLUMN     "queryCount" INTEGER NOT NULL DEFAULT 0;
